name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
      - master
  pull_request:
    branches:
      - main
      - dev
      - master

jobs:
  lint-and-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Code (ESLint)
        run: yarn lint

      - name: Format Code (Prettier)
        run: yarn format

      - name: Type Check (TypeScript)
        run: yarn tsc --noEmit

      - name: Run Tests
        run: yarn test --passWithNoTests

  build-and-deploy:
    name: Build, Push Docker Image & Deploy
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/job-recommender-backend .

      - name: Push Docker Image
        run: docker push your-dockerhub-username/job-recommender-backend
